// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using truyenthongso.Models;

#nullable disable

namespace truyenthongso.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250614030956_dbnew0616share")]
    partial class dbnew0616share
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("truyenthongso.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("truyenthongso.Models.Comment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Post_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("PublicId_id")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Url")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("User_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("Post_id");

                    b.HasIndex("User_id");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("truyenthongso.Models.CommentDescription", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("CommentDescript3_2")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("CommentDescription_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Comment_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("User_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("Comment_id");

                    b.HasIndex("User_id");

                    b.ToTable("CommentDescription");
                });

            modelBuilder.Entity("truyenthongso.Models.Complaints", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool?>("Action")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int?>("Author")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PublicId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Url")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("User_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("User_id");

                    b.ToTable("complaints");
                });

            modelBuilder.Entity("truyenthongso.Models.Friendship", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("UserId1")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("UserId2")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId2");

                    b.ToTable("friendships");
                });

            modelBuilder.Entity("truyenthongso.Models.Group", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("truyenthongso.Models.Group_Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int?>("group_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("role_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("group_id");

                    b.HasIndex("role_id");

                    b.ToTable("groupRoles");
                });

            modelBuilder.Entity("truyenthongso.Models.Interest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("User_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("User_id");

                    b.ToTable("interests");
                });

            modelBuilder.Entity("truyenthongso.Models.Like", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Post_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("User_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int?>("status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("Post_id");

                    b.HasIndex("User_id");

                    b.ToTable("likes");
                });

            modelBuilder.Entity("truyenthongso.Models.NewspaperSource", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("NewsSourceProvider_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("NewspaperType_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("Status")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Url")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("NewsSourceProvider_id");

                    b.HasIndex("NewspaperType_id");

                    b.ToTable("newspaperSources");
                });

            modelBuilder.Entity("truyenthongso.Models.NewspaperType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.ToTable("newspaperTypes");
                });

            modelBuilder.Entity("truyenthongso.Models.NewsSourceProvider", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Website")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.ToTable("newsSourceProviders");
                });

            modelBuilder.Entity("truyenthongso.Models.Notifition", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Use_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("Use_id");

                    b.ToTable("notifitions");
                });

            modelBuilder.Entity("truyenthongso.Models.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool?>("Action")
                        .HasColumnType("NUMBER(1)");

                    b.Property<float?>("AverageiewTime")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<int?>("Category_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("User_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Views")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("Category_id");

                    b.HasIndex("User_id");

                    b.ToTable("posts");
                });

            modelBuilder.Entity("truyenthongso.Models.Post_Image", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Post_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("PublicId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Url")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int?>("postid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("postid");

                    b.ToTable("postImages");
                });

            modelBuilder.Entity("truyenthongso.Models.Rating", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Start")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("User_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("User_id");

                    b.ToTable("ratings");
                });

            modelBuilder.Entity("truyenthongso.Models.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Url")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("truyenthongso.Models.Shere", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Post_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("User_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int?>("status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("title")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("Post_id");

                    b.HasIndex("User_id");

                    b.ToTable("sheres");
                });

            modelBuilder.Entity("truyenthongso.Models.Tag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("truyenthongso.Models.Tag_Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Post_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Tag_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("Post_id");

                    b.HasIndex("Tag_id");

                    b.ToTable("tagPosts");
                });

            modelBuilder.Entity("truyenthongso.Models.Token", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("token")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<int?>("userid")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("tokens");
                });

            modelBuilder.Entity("truyenthongso.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool>("Action")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Age")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("BlockComplaints")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("City")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Commune")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Complaints")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("District")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FullName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Image")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Password")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool?>("Paythefee")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("PublicId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Start")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("deleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int?>("role_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("truyenthongso.Models.Comment", b =>
                {
                    b.HasOne("truyenthongso.Models.Post", "post")
                        .WithMany("Comments")
                        .HasForeignKey("Post_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Comments")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.CommentDescription", b =>
                {
                    b.HasOne("truyenthongso.Models.Comment", "comment")
                        .WithMany("CommentDescriptions")
                        .HasForeignKey("Comment_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("CommentDescriptions")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("comment");

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Complaints", b =>
                {
                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Complaintss")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Friendship", b =>
                {
                    b.HasOne("truyenthongso.Models.User", "user1")
                        .WithMany("Friendships1")
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user2")
                        .WithMany("Friendships2")
                        .HasForeignKey("UserId2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user1");

                    b.Navigation("user2");
                });

            modelBuilder.Entity("truyenthongso.Models.Group_Role", b =>
                {
                    b.HasOne("truyenthongso.Models.Group", "group")
                        .WithMany("Group_Roles")
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.Role", "role")
                        .WithMany("Group_Roles")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("group");

                    b.Navigation("role");
                });

            modelBuilder.Entity("truyenthongso.Models.Interest", b =>
                {
                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Interests")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Like", b =>
                {
                    b.HasOne("truyenthongso.Models.Post", "post")
                        .WithMany("Likes")
                        .HasForeignKey("Post_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Likes")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.NewspaperSource", b =>
                {
                    b.HasOne("truyenthongso.Models.NewsSourceProvider", "newsSourceProvider")
                        .WithMany("NewspaperSources")
                        .HasForeignKey("NewsSourceProvider_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.NewspaperType", "newspaperType")
                        .WithMany("NewspaperSources")
                        .HasForeignKey("NewspaperType_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("newsSourceProvider");

                    b.Navigation("newspaperType");
                });

            modelBuilder.Entity("truyenthongso.Models.Notifition", b =>
                {
                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Notifitions")
                        .HasForeignKey("Use_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Post", b =>
                {
                    b.HasOne("truyenthongso.Models.Category", "category")
                        .WithMany("Posts")
                        .HasForeignKey("Category_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Posts")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("category");

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Post_Image", b =>
                {
                    b.HasOne("truyenthongso.Models.Post", "post")
                        .WithMany("Post_Images")
                        .HasForeignKey("postid");

                    b.Navigation("post");
                });

            modelBuilder.Entity("truyenthongso.Models.Rating", b =>
                {
                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Ratings")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Shere", b =>
                {
                    b.HasOne("truyenthongso.Models.Post", "post")
                        .WithMany("Sheres")
                        .HasForeignKey("Post_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Sheres")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Tag_Post", b =>
                {
                    b.HasOne("truyenthongso.Models.Post", "post")
                        .WithMany("TagPosts")
                        .HasForeignKey("Post_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.Tag", "tag")
                        .WithMany("TagPosts")
                        .HasForeignKey("Tag_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("post");

                    b.Navigation("tag");
                });

            modelBuilder.Entity("truyenthongso.Models.Token", b =>
                {
                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("tokens")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.User", b =>
                {
                    b.HasOne("truyenthongso.Models.Role", "role")
                        .WithMany("Users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("role");
                });

            modelBuilder.Entity("truyenthongso.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("truyenthongso.Models.Comment", b =>
                {
                    b.Navigation("CommentDescriptions");
                });

            modelBuilder.Entity("truyenthongso.Models.Group", b =>
                {
                    b.Navigation("Group_Roles");
                });

            modelBuilder.Entity("truyenthongso.Models.NewspaperType", b =>
                {
                    b.Navigation("NewspaperSources");
                });

            modelBuilder.Entity("truyenthongso.Models.NewsSourceProvider", b =>
                {
                    b.Navigation("NewspaperSources");
                });

            modelBuilder.Entity("truyenthongso.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Post_Images");

                    b.Navigation("Sheres");

                    b.Navigation("TagPosts");
                });

            modelBuilder.Entity("truyenthongso.Models.Role", b =>
                {
                    b.Navigation("Group_Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("truyenthongso.Models.Tag", b =>
                {
                    b.Navigation("TagPosts");
                });

            modelBuilder.Entity("truyenthongso.Models.User", b =>
                {
                    b.Navigation("CommentDescriptions");

                    b.Navigation("Comments");

                    b.Navigation("Complaintss");

                    b.Navigation("Friendships1");

                    b.Navigation("Friendships2");

                    b.Navigation("Interests");

                    b.Navigation("Likes");

                    b.Navigation("Notifitions");

                    b.Navigation("Posts");

                    b.Navigation("Ratings");

                    b.Navigation("Sheres");

                    b.Navigation("tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
