// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using truyenthongso.Models;

#nullable disable

namespace truyenthongso.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260428020610_icondb")]
    partial class icondb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("truyenthongso.Models.Articles_Viewed", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("post_id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("post_id");

                    b.HasIndex("user_id");

                    b.ToTable("articles_Viewedss");
                });

            modelBuilder.Entity("truyenthongso.Models.Behavioral_Analysis", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.HasIndex("user_id");

                    b.ToTable("behavioral_Analysess");
                });

            modelBuilder.Entity("truyenthongso.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("truyenthongso.Models.Citys", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("nation_id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("nation_id");

                    b.ToTable("citys");
                });

            modelBuilder.Entity("truyenthongso.Models.Comment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Post_id")
                        .HasColumnType("int");

                    b.Property<string>("PublicId_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("Post_id");

                    b.HasIndex("User_id");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("truyenthongso.Models.CommentDescription", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("CommentDescript3_2")
                        .HasColumnType("int");

                    b.Property<int?>("CommentDescription_id")
                        .HasColumnType("int");

                    b.Property<int?>("Comment_id")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("descript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("CommentDescript3_2");

                    b.HasIndex("CommentDescription_id");

                    b.HasIndex("Comment_id");

                    b.HasIndex("User_id");

                    b.ToTable("CommentDescription");
                });

            modelBuilder.Entity("truyenthongso.Models.Communes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("city_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("district_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("city_id");

                    b.HasIndex("district_id");

                    b.ToTable("communes");
                });

            modelBuilder.Entity("truyenthongso.Models.Complaints", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool?>("Action")
                        .HasColumnType("bit");

                    b.Property<int?>("Author")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("User_id");

                    b.ToTable("complaints");
                });

            modelBuilder.Entity("truyenthongso.Models.Districts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("city_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("city_id");

                    b.ToTable("districts");
                });

            modelBuilder.Entity("truyenthongso.Models.Friendship", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.Property<int?>("UserId2")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId2");

                    b.ToTable("friendships");
                });

            modelBuilder.Entity("truyenthongso.Models.Group", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("truyenthongso.Models.Group_Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("group_id")
                        .HasColumnType("int");

                    b.Property<int?>("role_id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("group_id");

                    b.HasIndex("role_id");

                    b.ToTable("groupRoles");
                });

            modelBuilder.Entity("truyenthongso.Models.Icon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("icons");
                });

            modelBuilder.Entity("truyenthongso.Models.Interest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("User_id");

                    b.ToTable("interests");
                });

            modelBuilder.Entity("truyenthongso.Models.Like", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Post_id")
                        .HasColumnType("int");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("Post_id");

                    b.HasIndex("User_id");

                    b.ToTable("likes");
                });

            modelBuilder.Entity("truyenthongso.Models.Nation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.ToTable("nations");
                });

            modelBuilder.Entity("truyenthongso.Models.NewspaperSource", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NewsSourceProvider_id")
                        .HasColumnType("int");

                    b.Property<int?>("NewspaperType_id")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("NewsSourceProvider_id");

                    b.HasIndex("NewspaperType_id");

                    b.ToTable("newspaperSources");
                });

            modelBuilder.Entity("truyenthongso.Models.NewspaperType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.ToTable("newspaperTypes");
                });

            modelBuilder.Entity("truyenthongso.Models.NewsSourceProvider", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.ToTable("newsSourceProviders");
                });

            modelBuilder.Entity("truyenthongso.Models.Notifition", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Use_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("Use_id");

                    b.ToTable("notifitions");
                });

            modelBuilder.Entity("truyenthongso.Models.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool?>("Action")
                        .HasColumnType("bit");

                    b.Property<float?>("AverageiewTime")
                        .HasColumnType("real");

                    b.Property<int?>("Category_id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.Property<int?>("Views")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("Category_id");

                    b.HasIndex("User_id");

                    b.ToTable("posts");
                });

            modelBuilder.Entity("truyenthongso.Models.Post_Image", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Post_id")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("postid")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("postid");

                    b.ToTable("postImages");
                });

            modelBuilder.Entity("truyenthongso.Models.PostUserTag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("post_id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("post_id");

                    b.HasIndex("user_id");

                    b.ToTable("postUserTags");
                });

            modelBuilder.Entity("truyenthongso.Models.Rating", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Start")
                        .HasColumnType("int");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("User_id");

                    b.ToTable("ratings");
                });

            modelBuilder.Entity("truyenthongso.Models.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("truyenthongso.Models.Shere", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Post_id")
                        .HasColumnType("int");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("status")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("Post_id");

                    b.HasIndex("User_id");

                    b.ToTable("sheres");
                });

            modelBuilder.Entity("truyenthongso.Models.Tag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("truyenthongso.Models.Tag_Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Post_id")
                        .HasColumnType("int");

                    b.Property<int?>("Tag_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("Post_id");

                    b.HasIndex("Tag_id");

                    b.ToTable("tagPosts");
                });

            modelBuilder.Entity("truyenthongso.Models.Token", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("tokens");
                });

            modelBuilder.Entity("truyenthongso.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool>("Action")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool?>("BlockComplaints")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Complaints")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Paythefee")
                        .HasColumnType("bit");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Start")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("role_id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("truyenthongso.Models.UserStoryView", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("post_id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("post_id");

                    b.HasIndex("user_id");

                    b.ToTable("userStoryViews");
                });

            modelBuilder.Entity("truyenthongso.Models.Articles_Viewed", b =>
                {
                    b.HasOne("truyenthongso.Models.Post", "post")
                        .WithMany("articles_Vieweds")
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("articles_Vieweds")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Behavioral_Analysis", b =>
                {
                    b.HasOne("truyenthongso.Models.Category", "category")
                        .WithMany("behavioral_Analyses")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("behavioral_Analyses")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("category");

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Citys", b =>
                {
                    b.HasOne("truyenthongso.Models.Nation", "nation")
                        .WithMany("citys")
                        .HasForeignKey("nation_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("nation");
                });

            modelBuilder.Entity("truyenthongso.Models.Comment", b =>
                {
                    b.HasOne("truyenthongso.Models.Post", "post")
                        .WithMany("Comments")
                        .HasForeignKey("Post_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Comments")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.CommentDescription", b =>
                {
                    b.HasOne("truyenthongso.Models.CommentDescription", "CommentDescription_id3")
                        .WithMany("commentDescriptions3")
                        .HasForeignKey("CommentDescript3_2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.CommentDescription", "CommentDescription_id2")
                        .WithMany("commentDescriptions2")
                        .HasForeignKey("CommentDescription_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.Comment", "comment")
                        .WithMany("CommentDescriptions")
                        .HasForeignKey("Comment_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("CommentDescriptions")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CommentDescription_id2");

                    b.Navigation("CommentDescription_id3");

                    b.Navigation("comment");

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Communes", b =>
                {
                    b.HasOne("truyenthongso.Models.Citys", "citys")
                        .WithMany("communes")
                        .HasForeignKey("city_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.Districts", "districts")
                        .WithMany("communes")
                        .HasForeignKey("district_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("citys");

                    b.Navigation("districts");
                });

            modelBuilder.Entity("truyenthongso.Models.Complaints", b =>
                {
                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Complaintss")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Districts", b =>
                {
                    b.HasOne("truyenthongso.Models.Citys", "citys")
                        .WithMany("districts")
                        .HasForeignKey("city_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("citys");
                });

            modelBuilder.Entity("truyenthongso.Models.Friendship", b =>
                {
                    b.HasOne("truyenthongso.Models.User", "user1")
                        .WithMany("Friendships1")
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user2")
                        .WithMany("Friendships2")
                        .HasForeignKey("UserId2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user1");

                    b.Navigation("user2");
                });

            modelBuilder.Entity("truyenthongso.Models.Group_Role", b =>
                {
                    b.HasOne("truyenthongso.Models.Group", "group")
                        .WithMany("Group_Roles")
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.Role", "role")
                        .WithMany("Group_Roles")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("group");

                    b.Navigation("role");
                });

            modelBuilder.Entity("truyenthongso.Models.Icon", b =>
                {
                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("iconss")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Interest", b =>
                {
                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Interests")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Like", b =>
                {
                    b.HasOne("truyenthongso.Models.Post", "post")
                        .WithMany("Likes")
                        .HasForeignKey("Post_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Likes")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.NewspaperSource", b =>
                {
                    b.HasOne("truyenthongso.Models.NewsSourceProvider", "newsSourceProvider")
                        .WithMany("NewspaperSources")
                        .HasForeignKey("NewsSourceProvider_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.NewspaperType", "newspaperType")
                        .WithMany("NewspaperSources")
                        .HasForeignKey("NewspaperType_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("newsSourceProvider");

                    b.Navigation("newspaperType");
                });

            modelBuilder.Entity("truyenthongso.Models.Notifition", b =>
                {
                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Notifitions")
                        .HasForeignKey("Use_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Post", b =>
                {
                    b.HasOne("truyenthongso.Models.Category", "category")
                        .WithMany("Posts")
                        .HasForeignKey("Category_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Posts")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("category");

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Post_Image", b =>
                {
                    b.HasOne("truyenthongso.Models.Post", "post")
                        .WithMany("Post_Images")
                        .HasForeignKey("postid");

                    b.Navigation("post");
                });

            modelBuilder.Entity("truyenthongso.Models.PostUserTag", b =>
                {
                    b.HasOne("truyenthongso.Models.Post", "post")
                        .WithMany("postUserTagss")
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("postUserTagss")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Rating", b =>
                {
                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Ratings")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Shere", b =>
                {
                    b.HasOne("truyenthongso.Models.Post", "post")
                        .WithMany("Sheres")
                        .HasForeignKey("Post_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("Sheres")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Tag_Post", b =>
                {
                    b.HasOne("truyenthongso.Models.Post", "post")
                        .WithMany("TagPosts")
                        .HasForeignKey("Post_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.Tag", "tag")
                        .WithMany("TagPosts")
                        .HasForeignKey("Tag_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("post");

                    b.Navigation("tag");
                });

            modelBuilder.Entity("truyenthongso.Models.Token", b =>
                {
                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("tokens")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.User", b =>
                {
                    b.HasOne("truyenthongso.Models.Role", "role")
                        .WithMany("Users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("role");
                });

            modelBuilder.Entity("truyenthongso.Models.UserStoryView", b =>
                {
                    b.HasOne("truyenthongso.Models.Post", "post")
                        .WithMany("userStoryViews")
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("truyenthongso.Models.User", "user")
                        .WithMany("userStoryViews")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("truyenthongso.Models.Category", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("behavioral_Analyses");
                });

            modelBuilder.Entity("truyenthongso.Models.Citys", b =>
                {
                    b.Navigation("communes");

                    b.Navigation("districts");
                });

            modelBuilder.Entity("truyenthongso.Models.Comment", b =>
                {
                    b.Navigation("CommentDescriptions");
                });

            modelBuilder.Entity("truyenthongso.Models.CommentDescription", b =>
                {
                    b.Navigation("commentDescriptions2");

                    b.Navigation("commentDescriptions3");
                });

            modelBuilder.Entity("truyenthongso.Models.Districts", b =>
                {
                    b.Navigation("communes");
                });

            modelBuilder.Entity("truyenthongso.Models.Group", b =>
                {
                    b.Navigation("Group_Roles");
                });

            modelBuilder.Entity("truyenthongso.Models.Nation", b =>
                {
                    b.Navigation("citys");
                });

            modelBuilder.Entity("truyenthongso.Models.NewspaperType", b =>
                {
                    b.Navigation("NewspaperSources");
                });

            modelBuilder.Entity("truyenthongso.Models.NewsSourceProvider", b =>
                {
                    b.Navigation("NewspaperSources");
                });

            modelBuilder.Entity("truyenthongso.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Post_Images");

                    b.Navigation("Sheres");

                    b.Navigation("TagPosts");

                    b.Navigation("articles_Vieweds");

                    b.Navigation("postUserTagss");

                    b.Navigation("userStoryViews");
                });

            modelBuilder.Entity("truyenthongso.Models.Role", b =>
                {
                    b.Navigation("Group_Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("truyenthongso.Models.Tag", b =>
                {
                    b.Navigation("TagPosts");
                });

            modelBuilder.Entity("truyenthongso.Models.User", b =>
                {
                    b.Navigation("CommentDescriptions");

                    b.Navigation("Comments");

                    b.Navigation("Complaintss");

                    b.Navigation("Friendships1");

                    b.Navigation("Friendships2");

                    b.Navigation("Interests");

                    b.Navigation("Likes");

                    b.Navigation("Notifitions");

                    b.Navigation("Posts");

                    b.Navigation("Ratings");

                    b.Navigation("Sheres");

                    b.Navigation("articles_Vieweds");

                    b.Navigation("behavioral_Analyses");

                    b.Navigation("iconss");

                    b.Navigation("postUserTagss");

                    b.Navigation("tokens");

                    b.Navigation("userStoryViews");
                });
#pragma warning restore 612, 618
        }
    }
}
